# GolangCI-Lint Configuration for Watchmen
# Schema: v2 (golangci-lint v2.0+)
# Reference: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.25.6"

linters:
  default: none
  enable:
    # ==========================================================================
    # Bugs & Error Detection
    # ==========================================================================
    - errcheck        # Check for unchecked errors
    - gosec           # Security-oriented linting
    - govet           # Reports suspicious constructs
    - staticcheck     # Go static analysis
    - bodyclose       # Check HTTP response body is closed
    - nilerr          # Finds code that returns nil even if error is not nil
    - noctx           # Finds HTTP requests without context.Context
    - rowserrcheck    # Check sql.Rows.Err is checked
    - sqlclosecheck   # Check sql.Rows and sql.Stmt are closed
    - durationcheck   # Check for two durations multiplied together

    - makezero        # Finds slice declarations not initialized with zero length
    - nosprintfhostport # Check for misuse of Sprintf for host:port

    # ==========================================================================
    # Performance
    # ==========================================================================
    - prealloc        # Find slice declarations that could be preallocated

    # ==========================================================================
    # Style & Formatting
    # ==========================================================================

    - misspell        # Find commonly misspelled English words
    - unconvert       # Remove unnecessary type conversions
    - unused          # Find unused code
    - ineffassign     # Detect ineffectual assignments
    - whitespace      # Check for unnecessary newlines

    # ==========================================================================
    # Complexity
    # ==========================================================================
    - cyclop          # Checks function and package cyclomatic complexity
    - funlen          # Detection of long functions
    - gocognit        # Cognitive complexity
    - gocyclo         # Cyclomatic complexity
    - nestif          # Reports deeply nested if statements

    # ==========================================================================
    # Error Handling
    # ==========================================================================
    - errorlint       # Find problems with error wrapping
    - wrapcheck       # Check errors are wrapped

    # ==========================================================================
    # Code Quality & Best Practices
    # ==========================================================================
    - goconst         # Find repeated strings that could be constants
    - gocritic        # Opinionated linter
    - revive          # Replacement for golint


    # ==========================================================================
    # Documentation
    # ==========================================================================
    - godot           # Check comments end with a period



  settings:
    # Complexity settings
    cyclop:
      max-complexity: 15


    funlen:
      lines: 100
      statements: 50
      ignore-comments: true

    gocognit:
      min-complexity: 20

    gocyclo:
      min-complexity: 15

    nestif:
      min-complexity: 5

    # Code quality settings
    goconst:
      min-len: 3
      min-occurrences: 3


    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too strict for this project

    revive:
      rules:
        - name: exported
          severity: warning
          arguments:
            - "checkPrivateReceivers"
        - name: var-naming
          severity: warning
        - name: package-comments
          severity: warning




    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true

    wrapcheck:
      ignore-package-globs:
        - github.com/hoangtran1411/watchman/*
        - github.com/spf13/cobra
        - github.com/spf13/viper

    gosec:
      excludes:
        - G104  # Unhandled errors (already covered by errcheck)
        - G304  # File path from variable (needed for config files)

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam       # Too strict
        - rangeValCopy    # Too strict for small structs

    misspell:
      locale: US

    godot:
      scope: declarations
      capital: true

  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      # Exclude directories
      - path: "vendor"
        linters:
          - ".*"
      - path: ".git"
        linters:
          - ".*"
      - path: "testdata"
        linters:
          - ".*"
      # Exclude test files from strict linting
      - path: "_test\\.go"
        linters:
          - wrapcheck
          - revive
          - funlen
          - gosec
          - errcheck
          - varnamelen



formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hoangtran1411/watchman

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
